sudo: required

language: android

android:
  components:
    - tools
    - build-tools-26.0.2
    - android-27
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
  licenses:
    - 'android-sdk-license.*'

cache:
  directories:
    - node_modules

before_install:
  # Add node.js dependencies.
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install nodejs
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - node -v && npm -v && yarn -v

script:
  - sudo npm install -g cordova
  - cordova -v
  - yarn
  - yarn build
  # Fix bug of https://github.com/apache/cordova-android/issues/521 temporarily.
  - rm -f ./platforms/android/CordovaLib/build.gradle && mv ./.travis/cordova.patforms.android.CordovaLib.build.gradle ./platforms/android/CordovaLib/build.gradle
  - yarn release:android
  - mv ./platforms/android/app/build/outputs/apk/release/app-release.apk whu-library-seat-mobile_$TRAVIS_TAG.apk

deploy:
  provider: releases
  skip-cleanup: true
  overwrite: true
  api_key: $GH_TOKEN
  file: 
    - "whu-library-seat-mobile_$TRAVIS_TAG.apk"
  on:
    tags: true
